### ISSUE TITLE
Not an issues

### ISSUE THREAD

**Issue by BagasNS** [yTakkar/React-Instagram-Clone-2.0#1]
i got this error when im try to start app, can u help me?
Error: Cannot find module './routes/user-routes'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\xampp\htdocs\React-Instagram-Clone-2.0-master\app.js:28:11)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by BagasNS** [comment]
fixed when im use win 7 32bit
