### ISSUE TITLE
Error on first run

### ISSUE THREAD

**Issue by srgtm** [yTakkar/React-Instagram-Clone-2.0#104]
Whichever port I'm using I'm still getting this error((
Error log:
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::9090
    at Server.setupListenHandle [as _listen2] (net.js:1280:14)
    at listenInCluster (net.js:1328:12)
    at Server.listen (net.js:1415:7)
    at Function.listen (/home/srgtm/Instagram/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/home/srgtm/Instagram/app.js:66:5)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
Emitted 'error' event at:
    at emitErrorNT (net.js:1307:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

**Comment by daarisameen** [comment]
Mention your port number in app.listen() function in app.js file.

**Comment by 0xhenrique** [comment]
Don't know if you're still facing this problem. But:
### You already have some service running in the port 9090
You have two options:
- You kill what's running in port 9090:
run `sudo ss -lptn 'sport = :9090'` to get the PID
run `kill -9 [PID number]` without the brackets

- The other option is to change the port in your app.js file if you want to keep the service that's already running on 9090.

**Comment by raghav8-ops** [comment]
.github/workflows/release.yml

**Comment by raghav8-ops** [comment]
****

**Comment by raghav8-ops** [comment]
Gajjela Lokesh reddy
