### ISSUE TITLE
please help. npm or yarn start error

### ISSUE THREAD

**Issue by Runixuz** [yTakkar/React-Instagram-Clone-2.0#14]
visual studio code

npm start

> react-instagram-clone-2.0@1.0.0 start D:\инс\React-Instagram-Clone-2.0-master (1)\React-Instagram-Clone-2.0-master
> nodemon app.js

[nodemon] 1.17.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node app.js`
module.js:549
    throw err;
    ^

Error: Cannot find module 'dotenv'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\инс\React-Instagram-Clone-2.0-master (1)\React-Instagram-Clone-2.0-master\app.js:1:63)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by Imronali** [comment]
+

**Comment by Imronali** [comment]
I also encountered that

**Comment by Imronali** [comment]
I could not fix it

**Comment by yTakkar** [comment]
Have you run `npm i`?
