### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Butonix** [yTakkar/React-Instagram-Clone-2.0#22]
Now if I publish a photo, it appears, but disappears when the page is refreshed!

**Comment by yTakkar** [comment]
When you add a post, it temporarily adds a post to home feed just to indicate that the post has been added.
And that added post can be found on your profile page

**Comment by Butonix** [comment]
Well thank you
And the last question, in seconds 40-50 break connection
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: Connection lost: The server closed the connection.
    at Protocol.end (C:\Users\sskat\Desktop\social\node_modules\mysql\lib\protocol\Protocol.js:113:13)
    at Socket.<anonymous> (C:\Users\sskat\Desktop\social\node_modules\mysql\lib\Connection.js:109:28)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1055:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by yTakkar** [comment]
Again, that's not a project's error.
Please search for this error
