### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Butonix** [yTakkar/React-Instagram-Clone-2.0#3]
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: Connection lost: The server closed the connection.
    at Protocol.end (C:\Users\rever\Desktop\test\node_modules\mysql\lib\protocol\Protocol.js:113:13)
    at Socket.<anonymous> (C:\Users\rever\Desktop\test\node_modules\mysql\lib\Connection.js:109:28)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[nodemon] app crashed - waiting for file changes before starting...

AND ERROR REGISTER

(node:10588) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: ER_NO_DEFAULT_FOR_FIELD: Field 'bio' doesn't have a default value
(node:10588) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by BagasNS** [comment]
Have you already imported db?

**Comment by Butonix** [comment]
Yes, the site is loading normally, but after 10-20 seconds the connection is broken

**Comment by Butonix** [comment]
I deleted it, there is not a gap anymore, but it's still not a solution to the problem
db.connect(err => {
  if(err){
    error(err.message)
  }
})

**Comment by yTakkar** [comment]
@Butonix I've solved the issue which is in the image
