### ISSUE TITLE
Error thrown when starting with yarn start

### ISSUE THREAD

**Issue by chaoman** [yTakkar/React-Instagram-Clone-2.0#36]
I followed along the installation instruction but encountered the following error when starting with yarn start command. 

I am running the following environment:

- Ubuntu 18
- npm 3.5.2
- yarn 1.6.0
- node 8.10.0

```
chaoman@localhost:~/React-Instagram-Clone-2.0$ sudo yarn start
yarn run v1.6.0
$ nodemon app.js
[nodemon] 1.17.5
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node app.js`
module.js:549
    throw err;
    ^

Error: Cannot find module '../../../config/mail'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/chaoman/React-Instagram-Clone-2.0/routes/api/others/edit-routes.js:6:10)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
[nodemon] app crashed - waiting for file changes before starting...
```
Do you have any clue when I couldn't start?

**Comment by yTakkar** [comment]
solved!!
https://github.com/yTakkar/React-Instagram-Clone-2.0/commit/8732744f4729ba8dac211624674a5fad1749453c

**Comment by chaoman** [comment]
Thanks for the quick action!!
