### ISSUE TITLE
please make tutorial on how to run on windows 10

### ISSUE THREAD

**Issue by pvresun** [yTakkar/React-Instagram-Clone-2.0#4]
please help me , how to run on windows 10 ?

**Comment by BagasNS** [comment]
U need to install node.js first on your windows https://nodejs.org/en/download/

**Comment by pvresun** [comment]
$ yarn start
yarn run v1.3.2
$ nodemon app.js
[nodemon] 1.15.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node app.js`
C:\Users\cloudways\Desktop\React-Instagram-Clone-2.0-master\node_modules\client-sessions\lib\client-sessions.js:548
    throw new Error("cannot set up sessions without a secret "+
    ^

Error: cannot set up sessions without a secret or encryptionKey/signatureKey pair
    at clientSessionFactory (C:\Users\cloudways\Desktop\React-Instagram-Clone-2.0-master\node_modules\client-sessions\lib\client-sessions.js:548:11)
    at Object.<anonymous> (C:\Users\cloudways\Desktop\React-Instagram-Clone-2.0-master\app.js:60:9)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
[nodemon] app crashed - waiting for file changes before starting...
