### ISSUE TITLE
getting error while signup

### ISSUE THREAD

**Issue by anupdineout** [yTakkar/React-Instagram-Clone-2.0#43]
{ Error: Cannot enqueue Query after fatal error.
    at Protocol._validateEnqueue (/Users/anup.kumar1/Documents/React-Instagram-Clone-2.0/node_modules/mysql/lib/protocol/Protocol.js:201:16)
    at Protocol._enqueue (/Users/anup.kumar1/Documents/React-Instagram-Clone-2.0/node_modules/mysql/lib/protocol/Protocol.js:139:13)
    at Connection.query (/Users/anup.kumar1/Documents/React-Instagram-Clone-2.0/node_modules/mysql/lib/Connection.js:208:25)
    at Promise (/Users/anup.kumar1/Documents/React-Instagram-Clone-2.0/config/db.js:18:8)
    at new Promise (<anonymous>)
    at Object.query (/Users/anup.kumar1/Documents/React-Instagram-Clone-2.0/config/db.js:17:10)
    at app.post (/Users/anup.kumar1/Documents/React-Instagram-Clone-2.0/routes/user/login-routes.js:42:21)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7) code: 'PROTOCOL_ENQUEUE_AFTER_FATAL_ERROR', fatal: false }

**Comment by yTakkar** [comment]
Have you followed all the steps
