### ISSUE TITLE
I am getting an error after npm start

### ISSUE THREAD

**Issue by ryptozee** [yTakkar/React-Instagram-Clone-2.0#44]
internal/modules/cjs/loader.js:573
    throw err;
    ^

Error: Cannot find module 'dotenv'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
    at Function.Module._load (internal/modules/cjs/loader.js:497:25)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/ryptozee/Documents/Projects/React-Instagram-Clone-2.0/app.js:9:1)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)

**Comment by yTakkar** [comment]
It's because dotenv module isn't installed.

**Comment by yTakkar** [comment]
Run `npm install` again to install.

**Comment by ryptozee** [comment]
I'm good on that now. Now the problem is error no secret key.

**Comment by yTakkar** [comment]
Can you provide the error log

**Comment by ryptozee** [comment]
Error: cannot set up sessions without a secret or
encryptionKey/signatureKey pair
    at clientSessionFactory
(/home/ryptozee/Documents/Projects/React-Instagram-Clone-2.0/node_modules/client-sessions/lib/client-sessions.js:548:11)
    at Object.<anonymous>
(/home/ryptozee/Documents/Projects/React-Instagram-Clone-2.0/app.js:49:9)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:719:10)
    at startup (internal/bootstrap/node.js:228:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:575:3)

**Comment by yTakkar** [comment]
You have to create a `.env` file as mentioned in step no. 4.
`client-session` expects a secret key, so add `SESSION_SECRET_LETTER` in `.env` file with any random key.

eg. `rkjbv42klrbc4hjrbv4jhrvb`,
`averysecretkey`

**Comment by ryptozee** [comment]
connect ECONNREFUSED 127.0.0.1:3306
(node:4235) [DEP0096] DeprecationWarning: timers.unenroll() is deprecated.
Please use clearTimeout instead.

**Comment by ryptozee** [comment]
I'm good now. It's running. Thanks.

**Comment by ryptozee** [comment]
Error changing avatar with a desired image

Error: Could not execute GraphicsMagick/ImageMagick: gm "convert"
"-quality" "100"
"/home/ryptozee/Documents/Projects/React-Instagram-Clone-2.0/dist/temp/9c65014079dd3c81dee1cae5c8238347"
"-resize" "200x200" "-gravity" "NorthWest"
"/home/ryptozee/Documents/Projects/React-Instagram-Clone-2.0/dist/users/31/avatar.jpg"
this most likely means the gm/convert binaries can't be found
    at ChildProcess.<anonymous>
(/home/ryptozee/Documents/Projects/React-Instagram-Clone-2.0/node_modules/gm/lib/command.js:232:12)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit
(internal/child_process.js:223:12)
    at onErrorNT (internal/child_process.js:394:16)
    at process._tickCallback (internal/process/next_tick.js:174:19)

**Comment by yTakkar** [comment]
Image Processing is indirectly handled by GraphicsMagick.
So install it as mentioned in the [requirement](https://github.com/yTakkar/React-Instagram-Clone-2.0#requirements) section
