### ISSUE TITLE
basic help needed

### ISSUE THREAD

**Issue by alexdiostia** [yTakkar/React-Instagram-Clone-2.0#57]
hello
seems you guys made it farther than me... but i face an issue at the step : "yarn start"
i followed all the steps described, successfully (from a raspberry Pi)...

i get the error shown below

would anyone have an idea ?

Thanks !
brgds
alex 

yarn run v1.9.4
$ ./node_modules/.bin/nodemon app.js
[nodemon] 1.18.4
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node app.js`
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::3306
    at Server.setupListenHandle [as _listen2] (net.js:1360:14)
    at listenInCluster (net.js:1401:12)
    at Server.listen (net.js:1485:7)
    at Function.listen (/var/www/html/insta/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/var/www/html/insta/app.js:66:5)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by StarAzure** [comment]
I am not familiar with raspberry pi. But on Windows, I use xamp which gives me localhost.. then follow the instructions in read me and should get you going on localhost:port in env js.

**Comment by alexdiostia** [comment]
> I am not familiar with raspberry pi. But on Windows, I use xamp which gives me localhost.. then follow the instructions in read me and should get you going on localhost:port in env js.

thanks. i had setup the preliminary config as mentioned (incl. an apache server,mysql db...). Maybe an issue coming from raspberry setup. I can indeed try from another OS... thanks
