### ISSUE TITLE
error starting app.js at shared web hosting

### ISSUE THREAD

**Issue by BagasNS** [yTakkar/React-Instagram-Clone-2.0#6]
can anyone guide me to run this app at my shared web hosting?i was follow the instruction but its still crash and this the error log on terminal.
/home/kingmed3/kingvisor.com/routes/user-routes.js:27
app.post('/user/username-checker', async (req, res) => {
                                         ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/kingmed3/kingvisor.com/app.js:28:11)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by yTakkar** [comment]
Does it support async/await?

**Comment by BagasNS** [comment]
how to check it?

**Comment by BagasNS** [comment]
never mind async/await start support at node.js v7 and my web using v5, thanks for info @yTakkar

**Comment by BagasNS** [comment]
running well on v9.5.0 web shared hosting. Great work!
