### ISSUE TITLE
SyntaxError: Unexpected token (

### ISSUE THREAD

**Issue by Nico-Lausch** [yTakkar/React-Instagram-Clone-2.0#7]
I get an error - after 
`npm start`

in ... routes\user-routes.js:27
```
app.post('/user/username-checker', async (req, res) => {
                                         ^
SyntaxError: Unexpected token (
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)

```

**Comment by BagasNS** [comment]
I sloved this problem with upgrade my node.js to 9.5.0

**Comment by BagasNS** [comment]
Here is my question https://github.com/yTakkar/React-Instagram-Clone-2.0/issues/6

**Comment by Nico-Lausch** [comment]
thanks for reply 👍 

hmmm, my current version is 
```
node -v
v6.9.1
```
downgrade?

**Comment by BagasNS** [comment]
Coz this project using async/await which node v6.9.1 doesn't support so u need to upgrade it hope u solve the problem

**Comment by Nico-Lausch** [comment]
thanks man, issue solved by

`choco install nodejs`

version now

`node -v
v9.5.0`
